# HTTP test file for AuctionsController
@id = 1

### Create auction
POST {{host}}/api/auctions
Authorization: Bearer {{jwt_token}}
Content-Type: application/json

{
  "artworkId": {{id}},
  "startDate": "2025-07-21T12:00:00Z",
  "endDate": "2025-07-28T12:00:00Z",
  "startingPrice": 100
}

###

### Update auction
PUT {{host}}/api/auctions/{{id}}
Authorization: Bearer {{jwt_token}}
Content-Type: application/json

{
  "artworkId": {{id}},
  "startDate": "2025-07-22T12:00:00Z",
  "endDate": "2025-07-29T12:00:00Z",
  "startingPrice": 1000
}

###

### Delete auction
DELETE {{host}}/api/auctions/{{id}}
Authorization: Bearer {{jwt_token}}

###

### Get all active auctions
GET {{host}}/api/auctions/active
Authorization: Bearer {{jwt_token}}

###

### Get my auctions
GET {{host}}/api/auctions/my
Authorization: Bearer {{jwt_token}}

###

### Get auction by id
GET {{host}}/api/auctions/{{id}}
Authorization: Bearer {{jwt_token}}