# HTTP test file for AuctionsController
@id = 1

POST http://localhost:5000/api/auctions
Content-Type: application/json

{
  "artworkId": {{id}},
  "startDate": "2025-07-21T12:00:00Z",
  "endDate": "2025-07-28T12:00:00Z",
  "startingPrice": 100
}

###

PUT http://localhost:5000/api/auctions/{{id}}
Content-Type: application/json

{
  "artworkId": {{id}},
  "startDate": "2025-07-22T12:00:00Z",
  "endDate": "2025-07-29T12:00:00Z",
  "startingPrice": 1000
}

###

DELETE http://localhost:5000/api/auctions/{{id}}

###

GET http://localhost:5000/api/auctions/active

###

GET http://localhost:5000/api/auctions/my

###

GET http://localhost:5000/api/auctions/{{id}}
