# HTTP test file for AuthController

### Register user
POST {{host}}/api/auth/register
Content-Type: application/json

{
  "userName": "testuser",
  "email": "test@example.com",
  "password": "Test123",
  "birthDate": "2000-01-01T00:00:00Z",
  "role": "Buyer"
}

###

### Login Buyer user (copy JWT from response and set it to {{jwt_token}} in the environment)
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "email": "Buyer@test.com",
  "password": "Buyer123!"
}

###

### Login Artist user (copy JWT from response and set it to {{jwt_token}} in the environment)
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "email": "Artist@test.com",
  "password": "Artist123!"
}

###

### Get current user (JWT needed from login)
GET {{host}}/api/auth/me
Authorization: Bearer {{jwt_token}}
Content-Type: application/json

###