# HTTP test file for BidsController

### Place a new bid
POST {{host}}/api/bids
Authorization: Bearer {{jwt_token}}
Content-Type: application/json

{
  "auctionId": 1,
  "amount": 101.50
}

###

### Get my bids
GET {{host}}/api/bids/my
Authorization: Bearer {{jwt_token}}