# HTTP test file for FavoritesController
@artworkId = 1

### Add artwork to favorites
POST {{host}}/api/favorites/{{artworkId}}
Authorization: Bearer {{jwt_token}}

###

### Remove artwork from favorites
DELETE {{host}}/api/favorites/{{artworkId}}
Authorization: Bearer {{jwt_token}}

###

### Get all favorites of current user
GET {{host}}/api/favorites
Authorization: Bearer {{jwt_token}}